### ISSUE TITLE
大佬，require_once怎么引入那两个文件，框架tp5.1.35,我下载下来文件放在了extend目录，require_once一直出错

### ISSUE THREAD

**Issue by qurge** [whm19940308/phpTools#1]

**Comment by qurge** [comment]
Fatal error: Cannot redeclare dump() (previously declared in D:\work\php\phpEnv\www\localhost\graduation_project\thinkphp\helper.php:330) in D:\work\php\phpEnv\www\localhost\graduation_project\extend\phpTools\functions.php on line 17

Fatal error: Uncaught Error: Class 'think\exception\ErrorException' not found in D:\work\php\phpEnv\www\localhost\graduation_project\thinkphp\library\think\Error.php:71 Stack trace: #0 D:\work\php\phpEnv\www\localhost\graduation_project\extend\phpTools\_autoload.php(21): think\Error::appError(2, 'include_once(D:...', 'D:\\work\\php\\php...', 21, Array) #1 D:\work\php\phpEnv\www\localhost\graduation_project\extend\phpTools\_autoload.php(21): include_once() #2 [internal function]: myAutoLoad('think\\exception...') #3 D:\work\php\phpEnv\www\localhost\graduation_project\thinkphp\library\think\Error.php(88): spl_autoload_call('think\\exception...') #4 [internal function]: think\Error::appShutdown() #5 {main} Next Error: Class 'think\exception\ErrorException' not found in D:\work\php\phpEnv\www\localhost\graduation_project\thinkphp\library\think\Error.php:71 Stack trace: #0 D:\work\php\phpEnv\www\localhost\graduation_project\extend\phpTools\_autoload.php(21): think\Error::appError(2, 'include_once(D:...', 'D:\\work\\php\\php.. in D:\work\php\phpEnv\www\localhost\graduation_project\thinkphp\library\think\Error.php on line 71

**Comment by mynameisyihan** [comment]
TP5 请用命名空间

**Comment by qurge** [comment]
> TP5 请用命名空间

好的，谢谢了
